logging:
  level:
    com.teles.chanchan: DEBUG
security:
  basic:
    enabled: false
  user:
    name: user
    password: churro$
management:
  context-path: /actuator
chanchan:
  io:
    output-path: null
  async:
    thread-pool-size: 20
    thread-name-prefix: ChanChan-Executor-
  client-four-chan:
    api-url: http://api.4chan.org
    cdn-url: http://i.4cdn.org
    request-delay: 100
    miniature-suffix: s.jpg
datasource:
  url: jdbc:mysql://localhost/chanchan
  class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
  username: root
  password: null
  pool:
    name: chanchan-dspool
  prepared-statements:
    cache: true
    size: 250
    sql-limit: 2048