server:
  contextPath:  

logging:
  level:
    com.teles.chanchan: DEBUG  

spring:
  data:
    mongodb:
      database: chanchan

security:
  basic:
    enabled: true
  user:
    name: user
    password: churro$

management:
  context-path: /actuator

chanchan:
  io:
    output-path: 
  async:
    thread-pool-size: 20
    thread-name-prefix: ChanChan-Executor-
  client-four-chan:
      api-url: http://api.4chan.org
      cdn-url: http://i.4cdn.org
      request-delay: 100
      miniature-suffix: s.jpg