logging:
  level:
    com.teles.chanchan: DEBUG

security:
  basic:
    enabled: false
  user:
    name: user
    password: churro$

management:
  context-path: /actuator

chanchan:
  async:
    thread-pool-size: 10
    thread-name-prefix: ChanchanTask-
  client-four-chan:
    api-url: http://api.4chan.org
    cdn-url: http://i.4cdn.org
    miniature-suffix: s.jpg

spring:
  data:
    mongodb:
      database: chanchan
  jackson:
    default-property-inclusion: non-null