version: '3'
services:
  webapp:
    image: 
      hltspires/chanchan
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image:
      mongo
    volumes:
      - /usr/local/mongo:/data/db
    ports:
      - 27017:27017