logging:
  level:
    com.teles.chanchan: DEBUG
chanchan:
  io:
    output-path: null
  async:
    thread-pool-size: 20
  client-four-chan:
    api-url: http://api.4chan.org
    cdn-url: http://i.4cdn.org
    miniature-suffix: s.jpg